# Generated by Django 4.2.10 on 2024-08-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_group_course_group_group_name'),
        ('users', '0003_remove_subscription_end_date_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.group'),
        ),
    ]
