# Generated by Django 4.2.10 on 2024-08-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='product',
            new_name='course',
        ),
    ]
