# Generated by Django 4.2.10 on 2024-08-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='userproductaccess',
            name='is_access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
    ]
