# Generated by Django 4.2.10 on 2024-08-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProductAccess',
        ),
    ]
