# Generated by Django 4.2.10 on 2024-08-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_userproductaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала курса'),
        ),
    ]
