# Generated by Django 4.2.10 on 2024-08-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='courses.course'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
