# Generated by Django 4.2.10 on 2024-08-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_group_course_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
